### ISSUE TITLE
FEAR issues

### ISSUE THREAD

**Issue by Kappa971** [kcat/dsoal#37]
I would like to report some problems encountered with FEAR:
1. With the Italian dubbing (but I have read that it also happens with the Russian one, so it could concern all non-English languages) and EAX enabled, the radio dialogues are silent. This also happens with Creative Alchemy, so it could be a game bug. It can be "solved" by converting the affected audio files from stereo to mono (all game sounds are mono, only radio dialogue is stereo).
2. The game menu sound is cut off.
3. With DSOAL_LOGLEVEL = 1, the log files get filled with the following error repeated indefinitely: 
   `2d14:err:dsound:EAX4Slot_Set Unexpected null effect propid 0x00000000`
   besides these two:
   `2d14:fixme:dsound:IKsPrivatePropertySetImpl_Get unsupported property: {f2957840-260c-11d1-a4d8-00c04fc28aca}`
   `2d14:err:dsound:DSBuffer_Initialize Panning for multi-channel buffers is not supported`

This is the complete log file: [dsoal_log.txt](https://github.com/kcat/dsoal/files/7770738/dsoal_log.txt)

**Comment by mirh** [comment]
1) sounds similar to the [max payne](https://github.com/kcat/dsoal/issues/23#issuecomment-822346605) problem, just in reverse
2) is it the same in XP?
3) second line should be irrelevant #3

**Comment by Kappa971** [comment]
1. FEAR without EAX works perfectly. With EAX enabled, the radio dialogues are silent, converting the audio files of the radios to mono, they work. Max Payne on the other hand crashes without ALchemy or with DSOAL without converting all audio files.
2. I don't know if it happens with XP but with ALchemy it doesn't.
3. Ok

**Comment by mirh** [comment]
I linked the "no sound" part of the max payne issue, not crashing. But who knows if they were ever supposed to work. Are english files already mono?

Everything else.. seems like we have three bugs:
* menu sound is cut off
* FXSLOT_EFFECT_NULL isn't handled
* panning for multi-channel buffers isn't supported (idk why it went from a fixme to a error in bae23cb766871cc77618d0e4f9c7d1c1a455dd7d)

**Comment by Kappa971** [comment]
> I linked the "no sound" part of the max payne issue, not crashing. But who knows if they were ever supposed to work. Are english files already mono?

Max Payne with DSOAL without converting the audio, crashes before the menu. With ALchemy it is fine without converting the audio, I don't know why. 
The audio files of the radio dialogue in English are in stereo but also work with EAX. Apparently they are the same as the Italian files, it is very strange.
All other sounds and dialogues are in mono and work without any conversion, even in Italian (and therefore I guess also in other languages).

> Everything else.. seems like we have three bugs:
> 
> * menu sound is cut off
> * FXSLOT_EFFECT_NULL isn't handled
> * panning for multi-channel buffers isn't supported (idk why it went from a fixme to a error in [bae23cb](https://github.com/kcat/dsoal/commit/bae23cb766871cc77618d0e4f9c7d1c1a455dd7d))

I think so.

**Comment by Kappa971** [comment]
With the latest build of DSOAL:

> 1. With the Italian dubbing (but I have read that it also happens with the Russian one, so it could concern all non-English languages) and EAX enabled, the radio dialogues are silent. This also happens with Creative Alchemy, so it could be a game bug. It can be "solved" by converting the affected audio files from stereo to mono (all game sounds are mono, only radio dialogue is stereo).

This problem is still present, but I think it is a strange problem with the game which is therefore not related to DSOAL.

> 2. The game menu sound is cut off.

This has been fixed, but now the menu sound has some reverb that shouldn't be there (that's not the only reverb problem encountered with the latest version of DSOAL, maybe I should open a new issue?)

> 3. With DSOAL_LOGLEVEL = 1, the log files get filled with the following error repeated indefinitely:
>    `2d14:err:dsound:EAX4Slot_Set Unexpected null effect propid 0x00000000`
>    besides these two:
>    `2d14:fixme:dsound:IKsPrivatePropertySetImpl_Get unsupported property: {f2957840-260c-11d1-a4d8-00c04fc28aca}`
>    `2d14:err:dsound:DSBuffer_Initialize Panning for multi-channel buffers is not supported`

Now the log file shows this:
`37cc:fixme:dsound:IKsPrivatePropertySetImpl_Get unsupported property: {f2957840-260c-11d1-a4d8-00c04fc28aca}`
`37cc:fixme:dsound:EAX4Slot_Query Unhandled effect propid: 0x00000000`
`37cc:err:dsound:DSBuffer_Initialize Panning for multi-channel buffers is not supported`

I'm not sure if I should keep this issue open.

**Comment by Kappa971** [comment]
I think I can close this issue for the moment.

**Comment by mirh** [comment]
https://web.archive.org/web/20050426013920/http://msdn.microsoft.com/archive/en-us/directx9_c/directx/htm/multichannelwavformats.asp
https://web.archive.org/web/20030819144319/http://msdn.microsoft.com/library/en-us/stream/hh/stream/aud-prop_8ugj.asp
I wonder if the first problem couldn't have something to do with some of this stuff I remembered from the max payne digging. 
Perhaps the game is debatably placing the radio chatter in the 3D space, and some of international publishers dubbed it in stereo. 
And even though that's not officially supported in ds8, retaining support for older versions meant that some skimpier driver devs eventually let it play even with the last version too. While Microsoft wrapper to WASAPI is very strict. 
Or anyhow something along those lines. 
...
Unless that also happened in XP, in which case I'm just blathering.

**Comment by Kappa971** [comment]
> https://web.archive.org/web/20050426013920/http://msdn.microsoft.com/archive/en-us/directx9_c/directx/htm/multichannelwavformats.asp https://web.archive.org/web/20030819144319/http://msdn.microsoft.com/library/en-us/stream/hh/stream/aud-prop_8ugj.asp I wonder if the first problem couldn't have something to do with some of this stuff I remembered from the max payne digging. Perhaps the game is debatably placing the radio chatter in the 3D space, and some of international publishers dubbed it in stereo. And even though that's not officially supported in ds8, retaining support for older versions meant that some skimpier driver devs eventually let it play even with the last version too. While Microsoft wrapper to WASAPI is very strict. Or anyhow something along those lines. ... Unless that also happened in XP, in which case I'm just blathering.

I used a tool to extract the game's audio files. I have compared the English and Italian audio files. The English radio dialogue audio files are in stereo and are also reproduced with hardware acceleration enabled in the menu. The Italian files look identical but they are not played. I ended up converting all Italian radio audio files to mono and the problem is solved. I could upload two example files here, maybe someone understands the difference between the two.

I don't know if this also happens in XP.

**Comment by mirh** [comment]
Then maybe the problem is not with stereo or mono?
Maybe it's sampling rate, bit depth or the codec? Despite the files being all .wavs, I see some of them are actually mp3 for instance.

**Comment by Kappa971** [comment]
> Then maybe the problem is not with stereo or mono? Maybe it's sampling rate, bit depth or the codec? Despite the files being all .wavs, I see some of them are actually mp3 for instance.

They are all audio files with MPEG Layer 3 codec with WAV container, they aren't WAV PCM. This also applies to English audio files. If you have FEAR in English, then check for yourself (you could also upload the English audio files here). Radio audio files usually end in "r" (<number>r.wav).
By converting these files to mono, they are also played with "Enable Sound Card = ON".
With "Enable sound card = OFF" stereo files are played correctly so there is some problem with DirectSound3D. It seems as if the game or DirectSound3D doesn't know which channel to play stereo tracks in, and therefore doesn't play anything. The strange thing is that stereo English audio files are played!
I compared the English and Italian files a while ago and I didn't notice any difference, maybe you or someone else may have better luck. I uploaded the Italian audio files for this reason.

**Comment by Choum28** [comment]
> > Then maybe the problem is not with stereo or mono? Maybe it's sampling rate, bit depth or the codec? Despite the files being all .wavs, I see some of them are actually mp3 for instance.
> 
> They are all audio files with MPEG Layer 3 codec with WAV container, they aren't WAV PCM. This also applies to English audio files. If you have FEAR in English, then check for yourself (you could also upload the English audio files here). Radio audio files usually end in "r" ([number]r.wav). Converting these files to mono, they are also played correctly (with "Enable Sound Card = ON"). With "Enable sound card = OFF" stereo files are played correctly so there is some problem with DirectSound3D. It seems as if the game or DirectSound3D doesn't know which channel to play stereo tracks in, and therefore doesn't play anything. The strange thing is that stereo English audio files are played! (with the "Enable Sound Card" option enabled). I compared the English and Italian files a while ago and I didn't notice any difference, maybe you or someone else may have better luck. I uploaded the Italian audio files for this reason.

I confirm the problem, as far as I remember this problem was already present when the game was out in 2006 (French version)
Which program did you use to convert all audio files ?

I also do not understand the bitrate of Audio game file.
2 Channel 16bits, 44100hz -> bitrate 112k?! for the english radio file (128k for localised version)

**Comment by Kappa971** [comment]
> I confirm the problem, as far as I remember this problem was already present when the game was out in 2006 (French version). THe problem is definitely due to the audio file itself (if you replace voice files with the english one in your localised FEARL.Arch00 package, the problem is gone. I also do not understand the bitrate of Audio game file. 2 Channel 16bits, 44100hz -> bitrate 112k?! for the english radio file (128k for localised version)
> 
> Which program did you use to convert all audio files ?

I used FEAR ArchiveEdit v2 to extract the audio files, opened them in Foobar2000, left only stereo files and converted them to mono via FFMPEG, I think with this parameter to be put in Foobar for conversion: `-i pipe:0 -y -ac 1 -c:a libmp3lame -ar 44100 -f wav %d` (maybe `-ab 112k` is also necessary, but I don't remember. Not all files have the same bitrate). 
I then created a new package with FEAR ArchiveEdit v2, copied to the game folder and added to the Default.archcfg file.

**Comment by Choum28** [comment]
> I used FEAR ArchiveEdit v2 to extract the audio files, opened them in Foobar2000, left only stereo files and converted them to mono via FFMPEG, I think with this parameter to be put in Foobar for conversion: `-i pipe:0 -y -ac 1 -c:a libmp3lame -ar 44100 -f wav %d` (maybe `-ab 112k` is also necessary, but I don't remember. Not all files have the same bitrate). I then created a new package with FEAR ArchiveEdit v2, copied to the game folder and added to the Default.archcfg file.

I tried with this parameters in a script file (to loop on all stereo file) .\ffmpeg.exe -i $file -ac 1 -c:a libmp3lame -ar 44100 -f wav c:\temp\$file
The file is corrupt according to footbar after conversion andI have no sound after the change ingame (even without HW mixing).

I also try with encoders : mp3_mf, file is not corrupt in footbar but no change ingame.
I also try PCM, the game skip dialog in this case.

**Comment by Kappa971** [comment]
> I tried with this parameters in a script file (to loop on all stereo file) .\ffmpeg.exe -i $file -ac 1 -c:a libmp3lame -ar 44100 -f wav c:\temp$file The file is corrupt according to footbar after conversion andI have no sound after the change ingame (even without HW mixing).

Try to specify the bitrate in the command as well, I don't remember if without specifying the bitrate, the resulting file takes the bitrate of the source file. It is an unusual audio format, Mpeg Layer 3 encoded WAV.
Also I just remembered that for the converted files I also used `Mp3tag` (otherwise the game would not read the new files).

**Comment by Choum28** [comment]
I try to set the bitrate to 128k no change, by default only the mp3_mf seems to keep the same bitrate.
What do you do with the mp3tag utility ?

**Comment by Kappa971** [comment]
> I try to set the bitrate to 128k no change, by default only the mp3_mf seems to keep the same bitrate. 

Try FFMPEG with Foobar2000, it works. When converting files, add a profile for FFMPEG (add the `ffmpeg.exe` path ) and copy the above command.

>What do you do with the mp3tag utility ?

If I remember correctly, I added all wav files to Mp3tag, right click and "Remove Tag", then right click and "Save ID3 to MP3 file".

**Comment by Choum28** [comment]
> > I try to set the bitrate to 128k no change, by default only the mp3_mf seems to keep the same bitrate.
> 
> Try FFMPEG with Foobar2000, it works. When converting files, add a profile for FFMPEG (add the `ffmpeg.exe` path ) and copy the above command.
> 
> > What do you do with the mp3tag utility ?
> 
> If I remember correctly, I added all wav files to Mp3tag, right click and "Remove Tag", then right click and "Save ID3 to MP3 file".

Thank you, I was able to make it work.
So to summarize for other people that will arrive here for the same issue :

- Extract all folders in the FEARL.Arch00 with FEAR ArchiveEdit v2 utility (ex:  c:\temp\FEARL\
- Open in footbar all file inside the voice folder (c:\temp\FEARL\voice), order them by channel (%channels%) and copy all stereo file in a new folder (c:\temp\stereo).
- Convert all those stereo file to mono with command line : 
-  .\ffmpeg.exe -i c:\temp\stereo\INPUTFILE -y -c:a mp3_mf -ac 1 -ar 44100 -f wav C:\temp\fix\OUTPUTFILE }
- Open all those new convert audio files (C:\temp\fix\) with MP3TAG then -> right click -> remove all tags (after conversion they all have a "RIFF" tag which seems to cause problem ingame).
- Copy paste those fix files (C:\temp\fix\) in the original extracted folder c:\temp\FEARL\voice, overwrite all files.
- Recreate a new FEARL.Arch00 archive with FEAR ArchiveEdit v2 utility and copy paste all folder inside c:\temp\FEARL\ in it.
- Save.
- Replace the FEARL.Arch00 in the game folder by the one you just created.

**Comment by Kappa971** [comment]
> * Convert all those stereo file to mono with command line :
> * .\ffmpeg.exe -i c:\temp\stereo\INPUTFILE -y -c:a mp3_mf -ac 1 -ar 44100 -f wav C:\temp\fix\OUTPUTFILE }

With Foobar2000 you can convert files automatically once you have used the above command in a custom profile for MMPEG. I used libmp3lame and it works. 
In your case you should create a batch file, otherwise you have to use that command for each wav file manually).

> You can also create an Arch00 patch file (by copying convert audio file (C:\temp\fix) only in a voice folder inside the arch00 file) , in that case do not forget to edit Default.archcfg to list your new Arch00 or the game will not load it.

This should be the recommended method, and also the most portable for those who want to share this "fix".

**Comment by mirh** [comment]
https://www.hwupgrade.it/forum/showthread.php?t=1095749
https://www.spieleforum.de/t/fear-probleme-mit-sound.763083/
https://www.gog.com/forum/fear_series/solution_windows_81_no_audio
https://web.archive.org/web/20030203033916/http://msdn.microsoft.com/library/en-us/stream/hh/stream/pcdesign_29if.asp
https://web.archive.org/web/20070102171430/http://www.softoutfit.com/hints.html#F.E.A.R.+%22No+Sound%22+Problem+Solved
So.. I did some more digging, and it seems like people were more or less also having the same problem in XP (unclear how much this was a codec problem, as opposed to hardware mixing itself)
On the other hand, reportedly you could just disable EAX and the thing suddenly worked again.

**Comment by Kappa971** [comment]
> https://www.hwupgrade.it/forum/showthread.php?t=1095749 https://www.spieleforum.de/t/fear-probleme-mit-sound.763083/ https://www.gog.com/forum/fear_series/solution_windows_81_no_audio https://web.archive.org/web/20030203033916/http://msdn.microsoft.com/library/en-us/stream/hh/stream/pcdesign_29if.asp https://web.archive.org/web/20070102171430/http://www.softoutfit.com/hints.html#F.E.A.R.+%22No+Sound%22+Problem+Solved So.. I did some more digging, and it seems like people were more or less also having the same problem in XP (unclear how much this was a codec problem, as opposed to hardware mixing itself) On the other hand, reportedly you could just disable "vendor-specific extensions" and the thing suddenly worked again.

What I think is:
1. the translators used a different mp3 codec
2. the translators messed with the mp3 tags

Do you have this WMFADist.exe file?

**Comment by mirh** [comment]
The translators (if not perhaps the publisher/developer itself) certainly screwed some setting, perhaps their encoder used stereo by default and they forgot to give it the right flags. And QA didn't catch this issue because this was DS3D\EAX\Soundblaster specific. 

But if this isn't a problem with anything the OS provides (missing mp3 decoder [aside](https://web.archive.org/web/20070207100450/http://www.project9k.jp/download/WMFADist.exe)), then it seems like there's actually another link of the chain that is broken and could be fixed instead of these conversions.

**Comment by Choum28** [comment]
The polish version suffers from the same problem, the polish version is using English voice with Polish subtitles.
The audio files are strictly the same as the English one, so the problem is inside the FEARL.Arch00

**Comment by ThreeDeeJay** [comment]
I know this is about non-English versions, but the issue also happens in the English version of the Extraction Point DLC. Someone made a fix and gave me permission to upload here https://community.pcgamingwiki.com/files/file/2600-fear-extraction-point-eax-fix/
Also, I added a reference in https://www.pcgamingwiki.com/wiki/F.E.A.R.#Audio

@kcat would it be feasible to make stereo sources that fail behave like mono sources? 🤔
Perhaps either by :
- Playing just the left (or right) channel
- Playing both channels in the same location as if all channels were merged in realtime
- Downmix the file before being loaded

**Comment by kcat** [comment]
> @kcat would it be feasible to make stereo sources that fail behave like mono sources?

I'm not sure what you mean by "stereo sources that fail". How are they failing? The
```
37cc:fixme:dsound:EAX4Slot_Query Unhandled effect propid: 0x00000000
```
message should be fixed, and 
```
37cc:err:dsound:DSBuffer_Initialize Panning for multi-channel buffers is not supported
```
is just saying (non-3D) multi-channel buffers won't pan. They still load and will play, it just will play normally and won't pan left or right (which the app probably won't do anyway, `DSBCAPS_CTRLPAN` is a default flag apps tend to set on non-3D buffers without any intention of panning).

**Comment by ThreeDeeJay** [comment]
Oh wait, so was this already fixed in a recent DSOAL/OpenAL Soft update?
I haven't tested it, but if I understand correctly, according to the first post, some radio dialogues are (/were?) silent because they're in stereo and both DSOAL and ALchemy fail to play them unless they're converted to mono. 
So perhaps I'm using "stereo sources" in the wrong context here, but my suggestion was basically allowing those stereo sound files to play (at least non-spatialized if they're 3D?), to work around what's apparently a bug in the game itself, not DSOAL/ALchemy emulation. 🤔

**Comment by kcat** [comment]
> Oh wait, so was this already fixed in a recent DSOAL/OpenAL Soft update?

Oh, no wait that fixme still happens. DSOAL handles queries natively since OpenAL's EAX API doesn't have it. I don't think it's a problem here though, since it has nothing to do with whether radio dialog plays or not.

> I haven't tested it, but if I understand correctly, according to the first post, some radio dialogues are (/were?) silent because they're in stereo and both DSOAL and ALchemy fail to play them unless they're converted to mono.

According to earlier posts, the English radio dialogs play fine, and they're in stereo too.

> The audio files of the radio dialogue in English (FEAR) are in stereo but also work with EAX.
...
> THe problem is definitely due to the audio file itself (if you replace voice files with the english one in your localised FEARL.Arch00 package, the problem is gone.
> I also do not understand the bitrate of Audio game file.
> 2 Channel 16bits, 44100hz -> bitrate 112k?! for the english radio file (128k for localised version)

It seems like a bug in the game, that for some reason the stereo english tracks don't trigger, and converting the localized tracks to mono works around. Unfortunately there's no error reported by DSOAL aside from the above, but those don't indicate any issue with the radio files. As far as DSOAL seems to be concerned, there's no issue loading and playing what it's told to, just for some reason it's not being told to play the regular localized radio tracks.

**Comment by ThreeDeeJay** [comment]
Ohhh, my b. I thought they meant they "reproduced" the _bug_ with the English files in stereo, but that actually meant _play_ the files. I was bamboozled for a second there so nevermind me and carry on 😅

**Comment by mirh** [comment]
> They are all audio files with MPEG Layer 3 codec with WAV container, they aren't WAV PCM. This also applies to English audio files. 

Uhm, no it doesn't (unless archiveedit does a hidden conversion behind). 
`10017.wav` which I extracted straight from the steam version (which AFAIK isn't localized) is actually a legit PCM file, as also manually evidenced if you check the hex format tag in the RIFF header.

**Comment by Kappa971** [comment]
> > They are all audio files with MPEG Layer 3 codec with WAV container, they aren't WAV PCM. This also applies to English audio files.
> 
> Uhm, no it doesn't (unless archiveedit does a hidden conversion behind). `10017.wav` which I extracted straight from the steam version (which AFAIK isn't localized) is actually a legit PCM file, as also manually evidenced if you check the hex format tag in the RIFF header.
> 
> It may be as well that only that is happy in stereo streams. https://learn.microsoft.com/en-us/windows/win32/api/mmreg/ns-mmreg-waveformatex

I just know that Foobar 2000 detects those files with mp3 codec. I similarly converted those files to mono with ffmpeg (mp3 with wav container). I've even used mp3tag to get ID3 information into new mono audio files (otherwise F.E.A.R. won't read them) so I can assume they use mp3 encoding (no idea why they used such a particular format).
The reason why localized stereo audio files are not being read by the game is still a mystery.

**Comment by mirh** [comment]
I got the same info (if less detailed) from mediainfo and gspot. 
I'd exhort you to please "run again" the extraction process from the start. 
If the byte at offset *0x14* is actually `0x55`, then I'm sure those are mp3s. But I'm very skeptical that you'll find english files that haven't just `0x1` there.

**Comment by Kappa971** [comment]
> I got the same info (if less detailed) from mediainfo and gspot. I'd exhort you to please "run again" the extraction process from the start. If the byte at offset _0x14_ is actually `0x55`, then I'm sure those are mp3s. But I'm very skeptical that you'll find english files that haven't just `0x1` there.

This is the original Italian audio, it's using MPEG-1 Layer 3 codec. I don't have the game in English.
![scr1](https://github.com/kcat/dsoal/assets/62349018/5a2e3d13-2469-4d97-88eb-b0b4807b8ece)
![scr2](https://github.com/kcat/dsoal/assets/62349018/c2b54f57-93bd-41f8-a69f-fcd0e3c45e9b)
![scr3](https://github.com/kcat/dsoal/assets/62349018/631e0b12-ee0c-4263-abf0-ff9dd5a022e6)

**Comment by Truth-Unknown** [comment]
I'm curious, since the audio is MP3 in WAVE files, maybe this version of the game is needing an ACM codec?
You can try the ACM codec from here: https://www.rarewares.org/mp3-lame-dshow-acm.php#lame-current-acm

**Comment by mirh** [comment]
LAME is for [encoding](https://web.archive.org/web/20060526104334/http://www.elecard.com/products/layer3encoder.shtml)-only (there's also a string inside the codec mentioning it)?
And as for decoding, `l3codeca.acm` is already being shipped in W10 (unless they somehow gimped/nerfed it with time).. if any `l3codecx.ax` seems to be missing. 

If only people could test with an x-fi on xp..

> I don't have the game in English.

Then how could you claim that the files are the same?

Btw it seems really strange that the RIFF container had to be stripped, considering every file I found had it, and that I'm not even sure wav files without are even supposed to be valid.

**Comment by Kappa971** [comment]
> Then how could you claim that the files are the same?

Because I had tried the game in English and the files were of the same format. I no longer have the game in English. You are claiming that the English version audio files are different, but I see no evidence for that. You should upload some pictures to prove it.

**Comment by Manu270891** [comment]
I can confirm that this issue is also present with the spanish dubbing.

**Comment by AdamOSDev** [comment]
I have the english version of F.E.A.R. and Extraction Point. I have missing radio dialog in both games with "enable HW mixing" enabled. If I disable it while the dialog is supposed to be playing, I can hear it fine. This happens with both Alchemy (1.45) and DSOAL (0.9.5) + OpenAL Soft (1.23.1). I'm on Windows 10 using the Steam version of the game.

Out of curiosity, I tried converting a radio dialog file that's supposed to play shortly after I load a save game in Extraction Point to a mono wav file according to @Choum28 instructions and it didn't make a difference. I made sure to create a new override/patch arch00 file and edit the Default.archcfg to load it.

@kcat any ideas?

**Comment by kcat** [comment]
Not really, unfortunately. Given the log in the first post, DSOAL isn't reporting any problem loading and playing sounds. If DSOAL was having a problem with them being MP3 encoded, I'd expect an error or fixme log message about it, which there doesn't appear to be. The problem seems to be outside of DSOAL, but if it works with HW mixing disabled, the game doesn't a problem decoding MP3s. An updated log using the `c++-rewrite` branch may provide more information, but I'm stumped currently.

**Comment by AdamOSDev** [comment]
I wonder if it's a codec/OS audio subsystem issue, maybe with l3codeca.acm specifically. I've seen quite a few threads that mention this codec. It's included in a redist called WMFADist.exe included with the game. It contains Windows Media Codec (Windows Media 7) among other media related things. Folks have reported installing it restored missing audio not only in this game but others from the era F.E.A.R. was released in. However, these threads were from 10+ years ago.

I've attached the redist. Maybe it might be of use to you. It won't install on Win10, but you can open the exe with 7-zip and poke around.
[WMFADist.zip](https://github.com/user-attachments/files/17538311/WMFADist.zip)

**Comment by Kappa971** [comment]
Updated log: [dsoal_log.txt](https://github.com/user-attachments/files/17599088/dsoal_log.txt)

**Comment by mirh** [comment]
> is just saying (non-3D) multi-channel buffers won't pan. 

I'd like to point out again https://github.com/kcat/dsoal/issues/18#issuecomment-1467126510 that's a bit of a problem

> It won't install on Win10,

http://www.komeil.com/blog/enable-fraunhofer-mp3-l3codecp-acm-windows

**Comment by Kappa971** [comment]
> > It won't install on Win10,
> 
> http://www.komeil.com/blog/enable-fraunhofer-mp3-l3codecp-acm-windows

As you know, the `WMFADist.exe` package is included in the game DVD. This is its content:

![Image](https://github.com/user-attachments/assets/1789f39c-0702-489a-87b9-a686fa9566cc)
It does not install in Windows 11 and I suspect some of those DLLs are important.
The `l3codeca.acm` and `l3codecp.acm` codecs should already be preinstalled in Windows 11 but the in-game radios are still silent.
Also the above site is obsolete because you can do the same operation from the K-Lite Codec configuration program:

![Image](https://github.com/user-attachments/assets/2198a55f-22ba-421a-916c-1e2ea5d6ade3)

**Comment by TyrannoWright** [comment]
Still kinda happens on English and with certain sound effects likely. Idk how many people overlooked it, but the Shogo easter egg room is broken with HW Mixing enabled.

https://streamable.com/36ve1h
[dsoal_error.txt](https://github.com/user-attachments/files/29935084/dsoal_error.txt)
